// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkpvtmtvlyopvfbxhnpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcHZ0bXR2bHlvcHZmYnhobnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjI0MjksImV4cCI6MjA2NzgzODQyOX0.DRTia1cTHySMo1bc16kD5t_sEpC4e0e7kJcsp8rECvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});